name: 'SODBuddy'
description: 'Enforces segregation of duties by checking the CODEOWNERS file and ensuring that no committer can approve or merge their own code.'
branding:
  icon: 'heart'
  color: 'red'
inputs:
  github-token:
    description: 'GitHub token to use for authentication'
    required: true
    default: ${{ github.token }}
  codeowners-file:
    description: 'Path to the CODEOWNERS file'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'



  
